### ISSUE TITLE
recurring appointments bug

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-ical-v3#3]
I would like to create recurring appointments in Apple Calender. To find out how these must be structured. Have I created an event with the ical v3 plugin, copied the uid and changed the event in iCal to repeat it 3 times.

When I query the appointment I don't get any meaningful values in the collection for the recurring rule. See Screenshot

Am I doing something wrong ?

![ical event](https://user-images.githubusercontent.com/6436037/83170066-3fcc6880-a114-11ea-9759-b9f67a90c8a6.png)

![get ical event](https://user-images.githubusercontent.com/6436037/83170089-465ae000-a114-11ea-993b-a158e96dec7e.png)

I assume that the plugin event kit is no longer maintained and the iCal v3 plugin is the new version as announced.

Also in the Event Kit plugin I could not solve the problem with the recurring appointments.

Thanks Armin

For easy reproducing, I've tried this code:

![code](https://user-images.githubusercontent.com/6436037/83170617-1cee8400-a115-11ea-934d-ab7df5fdbd45.png)

`C_OBJECT($status;$status2)
$status:=iCal Request permisson 

If ($status.success)
	
	$options:=New object
	  // this is my calendar id
	$options.calendar:=New object("uid";"2C0977EB-A1A6-4084-8EB0-46BFBC7D0FE5")
	$options.title:="TEST EVENT "+String(Current time)
	$options.startDate:=Current date
	$options.endDate:=Current date+1
	$options.isAllDay:=True
	
	$status:=iCal Create event ($options)
	
	  // Yes success event is created
	  // now at the debugger breakpoint, I've chanded the event in iCal to see, what comes back when 
	// I set a recurring rule and change the Allday to single day with time
	
	If ($status.success)
		$options2:=New object
		$options2.calendar:=New object("uid";"2C0977EB-A1A6-4084-8EB0-46BFBC7D0FE5")
		$options2.uid:=$status.event.uid
		
		$status2:=iCal Get event property ($options2)
	End if 
	
End if `

**Comment by miyako** [comment]
When you configure the event recurrence in Calendar app, for example, "every day, end after 3 times". the event ID does not change, but you can no longer find it directly by its primary key, for instance, with "iCal Get event property" or "iCal Set event property".


To study the "recurrence" object, you can query for it by data range.

```
events[0].recurrenceRule.recurrenceType // Daily
events[0].recurrenceRule.recurrenceInterval // every day
```

So "what about the 'end after 3 times' setting?", you might ask.

I would expect it to be in "recurrenceRule.recurrenceEnd", which includes properties such as "usesEndDate", "endDate", "occurrenceCount". But the plugin returns an empty object. Looks like a bug? But in Xcode, the object itself is 0x0.

So maybe this information is unreliable; reading the header files, I suspect it is only used for initialisation. 

But to create a daily event for 3 times:

```
$options:=New object
$options.calendar:=New object("title";"TEST")
$options.title:="TEST R. EVENT"
$options.startDate:=Current date
$options.endDate:=Current date+1
$options.isAllDay:=True
$options.recurrenceRule:=New object
$options.recurrenceRule.recurrenceType:=0  //Daily
$options.recurrenceRule.recurrenceInterval:=1//every day
$options.recurrenceRule.recurrenceEnd:=New object
$options.recurrenceRule.recurrenceEnd.occurrenceCount:=3
	
$status:=iCal Create event ($options)
```

Interestingly, the status object describes the recurrence rule correctly, but when I do a query, I get a null "recurrenceRule.recurrenceEnd".
